### ISSUE TITLE
How do I add external fonts to be used?

### ISSUE THREAD

**Issue by shift-eleven** [drewnoakes/figgle#10]
I wish to use some external figlet fonts to accompany the current ones available, although the readme doesn't specify how I could do this. Any help is appreciated.

**Comment by drewnoakes** [comment]
Great question. Here's how you would do it:

```c#
using var fontStream = System.IO.File.OpenRead("myfont.flf");
var font = FiggleFontParser.Parse(fontStream);
var text = font.Render("Hello World, from My Font");
```

I added this as an example to the README as well.

If you think those fonts should be added to this library, please comment on #2.
