### ISSUE TITLE
NuGet package supporting netstandard 2.0

### ISSUE THREAD

**Issue by akoken** [drewnoakes/figgle#17]
Hello @drewnoakes 

Thank you for this cool library! Our CI/CD pipeline fails at docker image scanning stage since netstandard 1.x has old and vulnerable packages. I wonder when you will publish next release. It seems you've already merged it :) 

![image](https://user-images.githubusercontent.com/2880254/209764268-c1bc1ed5-42dd-4fe3-bcde-64bea1d94f34.png)

![image](https://user-images.githubusercontent.com/2880254/209764488-9e3397ca-39f5-4b0a-a120-0f86b2c4188e.png)

**Comment by drewnoakes** [comment]
Thanks for the nudge. Released in 0.4.3.
