### ISSUE TITLE
Installing nuget package adds tons of unnecessary references

### ISSUE THREAD

**Issue by errantmind** [drewnoakes/figgle#3]
Hey, when installing Figgle using nuget a bunch of unnecessary references are added to the project.  None of these references are actually needed except Figgle.  These references make it look suspicious because a lot of them are cryptography related and other stuff unrelated to Figgle's core function.

edit: or maybe it does need all those references, in that case, why?

**Comment by drewnoakes** [comment]
Are you referencing Figgle from a .NET Core project?

**Comment by errantmind** [comment]
No, regular .Net 4.6.2 .  Maybe the references are needed? Just seems like
a lot for ascii text generation

**Comment by drewnoakes** [comment]
Totally agree they should not be there. I've seen this with other libraries. Fix/workaround for now is to target both `netstandard1.3` and `net45` (or similar) in the csproj and package. I'll get a new version out.

**Comment by errantmind** [comment]
The timeline, for clarity, is:
1. Add figgle nuget package to project
2. 20+ dll references added to References and packages.config

**Comment by errantmind** [comment]
Appreciate the explanation. I like the project, thanks for putting it
together

**Comment by drewnoakes** [comment]
Please try out version 0.3.0 from NuGet. I believe the problem should be resolved now.

**Comment by drewnoakes** [comment]
(You may have to wait a few minutes before it appears in the index)

**Comment by drewnoakes** [comment]
Did you get a chance to test this?

**Comment by errantmind** [comment]
Not just yet but I'll be able to this afternoon

**Comment by errantmind** [comment]
Hey, the fix looks good.  There is still one reference that gets added
(aside from Figgle itself) which is "System.IO.Compression".  Not sure if
this is necessary but there is a lot less clutter now.

Thanks,
-- James

**Comment by errantmind** [comment]
Actually, I'm not getting an exception:

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.IO.Compression,
Version=4.1.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one
of its dependencies. The system cannot find the file specified.
  Source=Figgle
  StackTrace:
   at Figgle.FiggleFonts.FontFactory(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey
key, Func`2 valueFactory)
   at Figgle.FiggleFonts.Lookup(String name)
   at Figgle.FiggleFonts.get_Standard()
   at Phoenix.Program.Main(String[] args) in
C:\Users\LocalUser\documents\visual studio
2017\Projects\Phoenix\Program.cs:line 14

Inner Exception 1:
FileNotFoundException: Could not load file or assembly
'System.IO.Compression, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system
cannot find the file specified.

**Comment by errantmind** [comment]
This looks like a problem on my part as my App.config was still contaminated from the previous version of Figgle.  Everything works fine now, this issue can be closed.

-- James
