### ISSUE TITLE
Make the lookup case insensitive

### ISSUE THREAD

**Issue by CodeBendor** [drewnoakes/figgle#9]
private static FiggleFont FontFactory(string name)
        {
            using var stream = typeof(FiggleFonts).GetTypeInfo().Assembly.GetManifestResourceStream("Figgle.Fonts.zip");
            using var zip = new ZipArchive(stream, ZipArchiveMode.Read);
            var entry = zip.Entries.ToDictionary(x=> x.FullName, x => x)
                .FirstOrDefault(x => x.Key.ToLowerInvariant().Replace(" ", string.Empty) == (name+".flf").ToLowerInvariant().Replace(" ", string.Empty)).Value;

            if (entry == null)
                throw new FiggleException($"No embedded font exists with name \"{name}\".");

            using var entryStream = entry.Open();
                
            return FiggleFontParser.Parse(entryStream, _stringPool);
        }

        public static FiggleFont Parse(string name)
        {
            var x = FontFactory(name);
            return x;
        }

**Comment by drewnoakes** [comment]
This adds a public `Parse` method. I'm curious why you need that, given all fonts embedded within the assembly are already exposed as properties on this type.

**Comment by drewnoakes** [comment]
> I used it in my command line version of the code

That makes sense.

> I wanted to use more fonts that I'd found and not have to predefined them

I'd expect you to do that with `FiggleFontParser` directly. `FiggleFonts` is intended to make it easy to access the bundled fonts. Perhaps the readme can be extended with an example that shows this.

**Comment by drewnoakes** [comment]
An example of reading custom fonts was added to the README some time ago.

https://github.com/drewnoakes/figgle#loading-external-fonts

I'll close this out.
